apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-nazar
spec:
  replicas: 2
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: testapi-nazar
  template:
    metadata:
      labels:
        app: testapi-nazar
    spec:
      containers:
        - image: nazarcodefresh/argo:5f4d1a497f02def08ccf9018
          name: testapi-nazar
          ports:
            - containerPort: 1700
