apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-nazar
spec:
  replicas: 20
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: testapi-nazar
  template:
    metadata:
      labels:
        app: testapi-nazar
    spec:
      containers:
        - image: olehzahnitko/argocd:1.1.17
          name: testapi-nazar
          ports:
            - containerPort: 1700
