apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi111
spec:
  replicas: 2
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
        - image: olehzahnitko/argocd:1.1.17
          name: testapi
          ports:
            - containerPort: 1700
