apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi111
spec:
  replicas: 3
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: testapi111
  template:
    metadata:
      labels:
        app: testapi111442
    spec:
      containers:
        - image: olehzahnitko/argocd:1.1.17
          name: testapi11122
          ports:
            - containerPort: 1700
